"""QC tools for the Lecture 14 agent demo — plain functions over a CSV.

Everything the agent is allowed to DO lives here, plus three tiny helpers the
ReAct loop needs: tell the model which tools exist (REACT_SYSTEM), spot a tool
call in the model's text (has_action / parse_action), and run it (run_tool).
Nothing in this file knows about the LLM.
"""
import csv
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))

# Spec limits (a real lab reads these from an SOP; hard-coded here to stay self-contained).
MASS_ERROR_ABS_MAX = 2.0        # |mass error| <= 2 ppm
RESOLUTION_MIN = 30_000         # resolution > 30,000
TIC_LOW, TIC_HIGH = 8.0, 12.0   # TIC (x1e6) within 8-12


DEFAULT_CSV = "qc_runs.csv"


def _resolve_csv(arg):
    """Turn whatever the model put in 'Action Input' into a real file path.

    The real fix for a model guessing filenames is data_inventory(), which tells
    it in the system prompt exactly which files exist. This is the safety net
    behind that: a model mid-conversation about a run may still write
    `Action Input: QC-04`, and a demo must not die on it, so anything that is not
    an existing file falls back to the one data file this demo ships with and
    says so in the observation.
    """
    candidate = (arg or "").strip().strip("'\"")
    if candidate:
        path = candidate if os.path.isabs(candidate) else os.path.join(HERE, candidate)
        if os.path.isfile(path):
            return path, None
        return (os.path.join(HERE, DEFAULT_CSV),
                f"(ignored argument {candidate!r} — not a file; used {DEFAULT_CSV})")
    return os.path.join(HERE, DEFAULT_CSV), None


def load_csv(arg, state):
    """Read the QC table from disk into memory (state['rows'])."""
    path, note = _resolve_csv(arg)
    if not os.path.isfile(path):
        return (f"ERROR: no QC data file at {path}. Expected {DEFAULT_CSV} "
                f"next to the demo scripts.")
    rows = []
    with open(path, newline="") as fh:
        for r in csv.DictReader(fh):
            rows.append(dict(
                run_id=r["run_id"],
                mass_error_ppm=float(r["mass_error_ppm"]),
                resolution=float(r["resolution"]),
                tic_1e6=float(r["tic_1e6"]),
            ))
    state["rows"] = rows
    msg = f"{len(rows)} runs loaded; columns: run_id, mass_error_ppm, resolution, tic_1e6"
    return msg + (" " + note if note else "")


def check_limits(arg, state):
    """Flag every run that breaks any spec limit; record the offenders."""
    rows = state.get("rows")
    if not rows:
        return "ERROR: load the data first."
    flagged = []
    for r in rows:
        why = []
        if abs(r["mass_error_ppm"]) > MASS_ERROR_ABS_MAX:
            why.append(f"mass error {r['mass_error_ppm']:+.1f} ppm (limit \u00b12)")
        if r["resolution"] < RESOLUTION_MIN:
            why.append(f"resolution {int(r['resolution']):,} (limit >30,000)")
        if not (TIC_LOW <= r["tic_1e6"] <= TIC_HIGH):
            why.append(f"TIC {r['tic_1e6']:.1f} (limit 8-12)")
        if why:
            flagged.append((r["run_id"], why))
    state["flagged"] = flagged
    if not flagged:
        return f"all {len(rows)} runs pass."
    return f"{len(rows) - len(flagged)}/{len(rows)} pass; " + " | ".join(
        f"{rid} FAILS: " + "; ".join(w) for rid, w in flagged)


def draft_summary(arg, state):
    """Draft a QC summary naming the failed run(s) and their exact values."""
    flagged = state.get("flagged")
    if flagged is None:
        return "ERROR: check the limits first."
    if not flagged:
        return "QC summary: all runs within spec. (Verify before release.)"
    lines = ["QC summary (DRAFT for human review):"]
    for rid, why in flagged:
        lines.append(f"  - {rid} is OUT OF SPEC: " + "; ".join(why) + ".")
    lines.append("  Recommend recalibrate + re-run; hold affected results. "
                 "Please verify before releasing any results.")
    return "\n".join(lines)


def data_inventory():
    """Describe the data files that actually exist, for the system prompt.

    THIS is the fix for the demo's original bug. An agent can only act on what
    its context says exists: the first prompt listed tools but never named a
    single file, so when asked about QC-04 the model had nothing to put in
    `Action Input` except the run id — and the tool tried to open a file called
    'QC-04'. Telling it what is on disk removes the guess entirely.

    Generated by reading the directory, so it can never drift from reality:
    add a CSV next to the scripts and the agent is told about it.
    """
    lines = []
    for fn in sorted(os.listdir(HERE)):
        if not fn.lower().endswith(".csv"):
            continue
        try:
            with open(os.path.join(HERE, fn), newline="") as fh:
                reader = csv.reader(fh)
                header = next(reader, [])
                n_rows = sum(1 for _ in reader)
        except OSError:
            continue
        lines.append(f"  - {fn} ({n_rows} rows) columns: " + ", ".join(header))
    if not lines:
        return ("Data files available: NONE were found next to the scripts. "
                "Say so rather than guessing a filename.\n")
    return ("Data files available to you (this is the complete list; never "
            "guess a filename that is not here):\n" + "\n".join(lines) + "\n")


# name -> (function, one-line description shown to the model)
TOOLS = {
    "load_csv":      (load_csv,      f"load one of the data files listed above into memory "
                                     f"(arg: a filename from that list; defaults to {DEFAULT_CSV})"),
    "check_limits":  (check_limits,  "flag runs that break any spec limit"),
    "draft_summary": (draft_summary, "draft a QC summary naming the failed runs"),
}


def run_tool(name, arg, state):
    """Run a tool and ALWAYS return a string.

    A tool that raises would kill the demo mid-sentence in front of the room, so
    every exception comes back as an 'ERROR: ...' observation instead. That is
    also what a real agent framework does — the model reads the error and tries
    something else, which is worth pointing out when it happens.
    """
    if name not in TOOLS:
        return (f"ERROR: no tool '{name}'. Available: "
                + ", ".join(TOOLS) + ".")
    try:
        return TOOLS[name][0](arg, state)
    except Exception as exc:                    # noqa: BLE001 - demo must survive
        return f"ERROR: {name} failed ({type(exc).__name__}: {exc})."


def has_action(text):
    """True if the model asked to call a tool (and hasn't already answered)."""
    return "Action:" in text and "Answer:" not in text


def parse_action(text):
    """Pull (tool_name, argument) out of the model's Action / Action Input lines."""
    name = re.search(r"Action:\s*(\w+)", text)
    arg = re.search(r"Action Input:\s*(.*)", text)
    a = arg.group(1).strip() if arg else ""
    if a.lower() in ("none", "n/a", ""):
        a = ""
    return (name.group(1) if name else ""), a


# The system prompt for stage 3: lists the tools and the strict ReAct format.
REACT_SYSTEM = (
    "You are a mass-spec QC assistant that can use tools.\n\n"
    + data_inventory() + "\n"
    "Tools:\n" + "\n".join(f"  - {n}: {d}" for n, (_, d) in TOOLS.items()) + "\n\n"
    "Reply in this format, one step at a time:\n"
    "Thought: <your reasoning>\n"
    "Action: <one tool name>\n"
    "Action Input: <argument, or none>\n\n"
    "I will reply with an 'Observation:' line. Repeat until you can finish with:\n"
    "Thought: <why you are done>\n"
    "Answer: <final answer, built ONLY from the observations>\n\n"
    "Never invent a number; every value must come from an Observation."
)
