#!/usr/bin/env python3
"""Dump each deck's text content to slides/txt/<deck>.txt for git diff + grep.

PPTX-first toolchain: slides/pptx/ decks are binary sources of truth edited in
PowerPoint, so these sidecar dumps are what makes a deck edit reviewable in a
diff and lets exercise-accuracy audits grep slide text, tables, and speaker
notes. Regenerate after ANY deck edit (and commit the .txt with the .pptx):

    python tools/pptx2txt.py --all
    python tools/pptx2txt.py slides/pptx/lecture05_cnns.pptx

The dump is deterministic: shapes in reading order (top, then left), tables as
pipe-separated rows, notes at the end of each slide block.
"""

import sys
from pathlib import Path

from pptx import Presentation

ROOT = Path(__file__).resolve().parent.parent
PPTX_DIR = ROOT / "slides" / "pptx"
TXT_DIR = ROOT / "slides" / "txt"


def _shape_lines(shape):
    if shape.has_text_frame:
        text = shape.text_frame.text.strip()
        if text:
            yield from text.splitlines()
    elif shape.has_table:
        for row in shape.table.rows:
            yield "| " + " | ".join(c.text.strip() for c in row.cells) + " |"
    elif shape.shape_type == 13:  # picture
        yield f"[image: {shape.name}]"
    if shape.shape_type == 6:  # group
        for sub in sorted(shape.shapes, key=_pos):
            yield from _shape_lines(sub)


def _pos(shape):
    return (shape.top or 0, shape.left or 0)


def dump(deck_path: Path) -> Path:
    prs = Presentation(str(deck_path))
    out = [f"# {deck_path.name} — {len(prs.slides)} slides",
           f"# (generated by tools/pptx2txt.py; do not hand-edit)", ""]
    for i, slide in enumerate(prs.slides, 1):
        out.append(f"--- slide {i} · layout: {slide.slide_layout.name} ---")
        for shape in sorted(slide.shapes, key=_pos):
            out.extend(_shape_lines(shape))
        if slide.has_notes_slide:
            notes = slide.notes_slide.notes_text_frame.text.strip()
            if notes:
                out.append("NOTES:")
                out.extend("  " + ln for ln in notes.splitlines())
        out.append("")
    TXT_DIR.mkdir(parents=True, exist_ok=True)
    dest = TXT_DIR / (deck_path.stem + ".txt")
    dest.write_text("\n".join(out))
    return dest


def main(argv):
    if len(argv) < 2 or argv[1] in ("-h", "--help"):
        print(__doc__)
        return 0
    targets = (sorted(PPTX_DIR.glob("lecture*.pptx")) if argv[1] == "--all"
               else [Path(a).resolve() for a in argv[1:]])
    for deck in targets:
        dest = dump(deck)
        print(f"{deck.name} -> {dest.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
